files:
   about-emercoin: {
      name: About Emercoin,
      meta: {
        title: About Emercoin - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   emercoin-api: {
      name: Emercoin API,
      meta: {
        title: Emercoin API - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   emercoin-press-kit: {
      name: Emercoin Press Kit,
      meta: {
        title: Emercoin Press Kit - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   links-resources: {
      name: Links & Resources,
      meta: {
        title: Links & Resources - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
