name: EmerDNS
files:
   050.emerdns-introduction: {
      name: EmerDNS Introduction,
      meta: {
        title: EmerDNS Introduction - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   100.i2p-domain-name-registration-based-on-blockchain: {
      name: I2P Domain Name Registration based on blockchain,
      meta: {
        title: I2P Domain Name Registration based on blockchain - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
