name: Running Emercoin
files:
   050.linux-quickstart: {
      name: Linux Quickstart,
      meta: {
        title: Linux Quickstart - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   100.command-line: {
      name: Command Line,
      meta: {
        title: Command Line - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   150.emercoin-conf: {
      name: emercoin.conf,
      meta: {
        title: Configuration - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   200.ports: {
      name: Ports,
      meta: {
        title: Ports - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   250.testnet: {
      name: Testnet,
      meta: {
        title: Testnet - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
