name: Running Emercoin
sort: 200
files:
   linux-quickstart: {
      name: Linux Quickstart,
      sort: 050,
      meta: {
        title: Linux Quickstart - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   command-line: {
      name: Command Line,
      sort: 100,
      meta: {
        title: Command Line - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   emercoin-conf: {
      name: emercoin.conf,
      sort: 150,
      meta: {
        title: Configuration - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   ports: {
      name: Ports,
      sort: 200,
      meta: {
        title: Ports - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   testnet: {
      name: Testnet,
      sort: 250,
      meta: {
        title: Testnet - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
