name: EmerSSL
files:
   emerssl-introduction: {
      name: EmerSSL Introduction,
      meta: {
        title: EmerSSL Introduction - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   emerssl-guide: {
      name: EmerSSL Guide,
      meta: {
        title: EmerSSL Guide - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   emerssl-infocard: {
      name: EmerSSL InfoCard,
      meta: {
        title: EmerSSL InfoCard - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   ports: {
      name: Ports,
      meta: {
        title: Ports - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   testnet: {
      name: Testnet,
      meta: {
        title: Testnet - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
