name: Mobile Wallets
sort: 050
files:
   emercoin-sw: {
      name: Emercoin SW,
      sort: 050,
      meta: {
        title: Emercoin SW - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   emercoin-one: {
      name: Emercoin One,
      sort: 100,
      meta: {
        title: Emercoin One - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   emercoin-basic: {
      name: Emercoin Basic,
      sort: 150,
      meta: {
        title: Emercoin Basic - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
