name: EmerDPO
files:
   050.emerdpo-introduction: {
      name: EmerDPO Introduction,
      meta: {
        title: EmerDPO Introduction - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   100.the-emerdpo-antifake-programme: {
      name: The EmerDPO Antifake Programme,
      meta: {
        title: The EmerDPO Antifake Programme - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   150.emerdpo-sn-publisher: {
      name: EmerDPO SN-Publisher,
      meta: {
        title: EmerDPO SN-Publisher - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
