name: Introduction
files:
   the-emc-currency: {
      name: The EMC Currency,
      meta: {
        title: The EMC Currency - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   specifications: {
      name: Emercoin Specifications,
      meta: {
        description: lorem ipsum
      }
    }
   technology-tree: {
      name: Emercoin Tech Tree,
      meta: {
        description: lorem ipsum
      }
    }
   security-principles: {
      name: Emercoin Security Principles,
      meta: {
        description: lorem ipsum
      }
    }
   roadmap-&-achievements: {
      name: Roadmap and Achievements,
      meta: {
        description: lorem ipsum
      }
    }
