name: EmerSSL
files:
   050.emerssl-introduction: {
      name: EmerSSL Introduction,
      meta: {
        title: EmerSSL Introduction - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   100.emerssl-guide: {
      name: EmerSSL Guide,
      meta: {
        title: EmerSSL Guide - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   150.emerssl-infocard: {
      name: EmerSSL InfoCard,
      meta: {
        title: EmerSSL InfoCard - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   200.ports: {
      name: Ports,
      meta: {
        title: Ports - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   250.testnet: {
      name: Testnet,
      meta: {
        title: Testnet - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
