name: Introduction
files:
   100.the-emc-currency: {
      name: The EMC Currency,
      meta: {
        title: The EMC Currency - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   100.specifications: {
      name: Emercoin Specifications,
      meta: {
        description: lorem ipsum
      }
    }
   150.technology-tree: {
      name: Emercoin Tech Tree (Dec 2017),
      meta: {
        description: lorem ipsum
      }
    }
   200.security-principles: {
      name: Emercoin Security Principles,
      meta: {
        description: lorem ipsum
      }
    }
   250.roadmap-&-achievements: {
      name: Roadmap and Achievements,
      meta: {
        description: lorem ipsum
      }
    }
