name: Blockchain Services
files:
   introduction-to-emercoin-services: {
      name: Introduction to Emercoin Services,
      meta: {
        title: Introduction to Emercoin Services - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   emernvs: {
      name: EmerNVS,
      meta: {
        title: EmerNVS - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   emerssh: {
      name: EmerSSH,
      meta: {
        title: EmerSSH - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   emerlnx: {
      name: EmerLNX,
      meta: {
        title: EmerLNX - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   emermagnet: {
      name: EmerMAGNET,
      meta: {
        title: EmerMAGNET - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
   enumer: {
      name: ENUMER,
      meta: {
        title: ENUMER - Emercoin Community Documentation,
        description: Emercoin Community Documentation,
        keywords: ,
        author: Emercoin Community
      }
    }
